export const locations = [
  {
    id: 1,
    name: "Rhapsody's",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦25,000",
    image: "/images/rhapsodys.jpg",
    mapUrl: "https://maps.app.goo.gl/Pbbuv6mMhYep1HnB8",
    category: "Late Night",
    description: "Upscale lounge with a lively atmosphere. Perfect for group dinners that turn into late-night parties.",
    menuHighlights: ["Prawn Pasta", "Rhapsody's Burger", "Chapman"],
  },
  {
    id: 2,
    name: "Sailors Lounge",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦18,000",
    image: "/images/sailors-lounge.jpg",
    mapUrl: "https://maps.app.goo.gl/rW6ykRMKmYKpqSVDA",
    category: "Date Night",
    description: "Famous waterfront lounge. Great for sunsets, live band music, and romantic evenings by the water.",
    menuHighlights: ["Grilled Croaker Fish", "Seafood Platter", "Calamari"],
  },
  {
    id: 3,
    name: "Hard Rock Cafe",
    type: "Island",
    area: "VI",
    price: "₦30,000",
    image: "/images/hard-rock.jpg",
    mapUrl: "https://maps.app.goo.gl/Q7Hjk5uCjSf4A37LA",
    category: "Late Night",
    description: "Global brand known for rock 'n' roll memorabilia, loud music, and American-style comfort food.",
    menuHighlights: ["Legendary Burger", "Nachos", "Hurricanes"],
  },
  {
    id: 4,
    name: "Purple Bistro",
    type: "Mainland",
    area: "Yaba",
    price: "₦8,000",
    image: "/images/purple-bistro.jpg",
    mapUrl: "https://maps.app.goo.gl/sEJ1KqHFZDmYG29t7",
    category: "Chill",
    description: "A student favorite with aesthetic purple lighting. Affordable fusion food and great vibes.",
    menuHighlights: ["Purple Special Rice", "Chicken Wings", "Pasta"],
  },
  {
    id: 5,
    name: "Danfo Bistros & Dives",
    type: "Island",
    area: "Ikoyi",
    price: "₦15,000",
    image: "/images/danfo-bistro.jpg",
    mapUrl: "https://maps.app.goo.gl/wpufUb6YgFDjaAMq8",
    category: "Cultural",
    description: "A quirky, Lagos-themed spot inspired by Danfo buses. Very colorful and Instagram-worthy.",
    menuHighlights: ["Ewa Agoyin Sandwich", "Suya Wings", "Zobo slush"],
  },
  {
    id: 6,
    name: "The Place",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦6,000",
    image: "/images/the-place.jpg",
    mapUrl: "https://maps.app.goo.gl/eHwxY4sZiQdzHhFn6",
    category: "Budget Eats",
    description: "The legendary spot for fast, reliable Nigerian food. Open late and always buzzing.",
    menuHighlights: ["Jollof Rice", "Asun", "Spaghetti Stir-fry"],
  },
  {
    id: 7,
    name: "Shiro Lagos",
    type: "Island",
    area: "VI",
    price: "₦40,000",
    image: "/images/shiro.jpg",
    mapUrl: "https://maps.app.goo.gl/CAksmM9Gid8DW4n2A",
    category: "Date Night",
    description: "Pan-Asian luxury dining with stunning high ceilings and giant statues. A top date spot.",
    menuHighlights: ["Sushi Platter", "Dim Sum", "Thai Green Curry"],
  },
  {
    id: 8,
    name: "Farmcity",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦12,000",
    image: "/images/farmcity.jpg",
    mapUrl: "https://maps.app.goo.gl/RkrGs74hiH5N8Ge18",
    category: "Late Night",
    description: "24-hour spot famous for seafood and active nightlife. Always busy, always loud.",
    menuHighlights: ["Grilled Catfish", "Prawns", "Fish Pepper Soup"],
  },
  {
    id: 9,
    name: "The Orchid Bistro",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦30,000",
    image: "/images/orchid-bistro.jpg",
    mapUrl: "https://maps.app.goo.gl/YJ3TpxKzE9pLw69z8",
    category: "Date Night",
    description: "A serene garden cafe hidden in Ikeja. Quiet, classy, and great for coffee dates.",
    menuHighlights: ["Full English Breakfast", "Lamb Chops", "Carrot Cake"],
  },
  {
    id: 10,
    name: "Bay Lounge",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦15,000",
    image: "/images/bay-lounge.jpg",
    mapUrl: "https://maps.app.goo.gl/4ZtUp3TyhjYeqDGz6",
    category: "Late Night",
    description: "Open-air lounge by the water. Romantic at night with live bands and cool breeze.",
    menuHighlights: ["BBQ Fish", "Peppered Snails", "Cocktails"],
  },
  {
    id: 11,
    name: "Circa Non Pareil",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦30,000",
    image: "/images/circa-non-pareil.jpg",
    mapUrl: "https://maps.app.goo.gl/hjcjrnQ3DyTearRQ9",
    category: "Date Night",
    description: "Multi-level luxury dining with ocean views. The architecture is stunning and perfect for proposals.",
    menuHighlights: ["Lobster Thermidor", "Lamb Shank", "Signature Cocktails"],
  },
  {
    id: 12,
    name: "Cactus Restaurant",
    type: "Island",
    area: "VI",
    price: "₦50,000",
    image: "/images/cactus.jpg",
    mapUrl: "https://maps.app.goo.gl/DBTe44reT2VxN7Hk9",
    category: "Chill",
    description: "A classic Lagos spot with a beautiful waterfront terrace. Great for Sunday brunch with family.",
    menuHighlights: ["Pizza", "Seafood Paella", "Red Velvet Cake"],
  },
  {
    id: 13,
    name: "The Grid",
    type: "Mainland",
    area: "Yaba",
    price: "₦15,000",
    image: "/images/the-grid.jpg",
    mapUrl: "https://maps.app.goo.gl/q5QvRjHfXwN8g6qd6",
    category: "Late Night",
    description: "One of the few upscale lounge experiences on the Mainland. Dark, moody, and great music.",
    menuHighlights: ["Grid Platter", "Burgers", "Long Island Iced Tea"],
  },
  {
    id: 14,
    name: "Black Bell",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦12,000",
    image: "/images/blackbell.jpg",
    mapUrl: "https://maps.app.goo.gl/4FdTr7JFQjdXa9De7",
    category: "Chill",
    description: "Reliable, tasty, and modern. A great spot for a casual dinner that feels slightly upscale.",
    menuHighlights: ["Jollof Rice & Turkey", "Alfredo Pasta", "Waffles"],
  },
  {
    id: 15,
    name: "Z Kitchen",
    type: "Island",
    area: "VI",
    price: "₦50,000",
    image: "/images/z-kitchen.jpg",
    mapUrl: "https://maps.app.goo.gl/bBpzeA9LNrhaZt2R7",
    category: "Date Night",
    description: "High-end contemporary dining. Known for incredible service and specific attention to detail.",
    menuHighlights: ["Short Ribs", "Seabass", "Chocolate Fondant"],
  },
  {
    id: 16,
    name: "Burg.Co",
    type: "Mainland",
    area: "Ikeja",
    price: "₦12,000",
    image: "/images/burg-co.jpg",
    mapUrl: "https://maps.app.goo.gl/cYq7F9WTBtK9vXK88",
    category: "Chill",
    description: "A minimalist burger joint with arguably the best smash burgers on the mainland.",
    menuHighlights: ["The OG Burger", "Truffle Fries", "Lotus Biscoff Shake"],
  },
  {
    id: 17,
    name: "Rufus & Bee",
    type: "Island",
    area: "Lekki",
    price: "₦15,000",
    image: "/images/rufus-bee.jpg",
    mapUrl: "https://maps.app.goo.gl/5hLaQ4d73Wky9ta69",
    category: "Activity",
    description: "Huge arcade and bowling alley. The ultimate 'play' date spot for adults and kids.",
    menuHighlights: ["Bowling", "Arcade Games", "Nachos"],
  },
  {
    id: 18,
    name: "HSE Gourmet",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦22,000",
    image: "/images/hse-gourmet.jpg",
    mapUrl: "https://maps.app.goo.gl/vHv4tn21yRU7Xcvs5",
    category: "Date Night",
    description: "Intimate comfort gourmet. Small space but big flavors, often called a hidden gem.",
    menuHighlights: ["Duck Pasta", "Mac & Cheese", "Prawn Tacos"],
  },
  {
    id: 19,
    name: "Ofada Boy",
    type: "Mainland",
    area: "Surulere",
    price: "₦7,000",
    image: "/images/ofadaboy.jpg",
    mapUrl: "https://maps.app.goo.gl/uK1BSuUP1x418aYr5",
    category: "Cultural",
    description: "The king of traditional Ofada rice. A very cultural setting with palm wine and local vibes.",
    menuHighlights: ["Ofada Rice", "Palm Wine", "Asun"],
  },
  {
    id: 20,
    name: "Kapadoccia",
    type: "Island",
    area: "VI",
    price: "₦30,000",
    image: "/images/kapadoccia.jpg",
    mapUrl: "https://maps.app.goo.gl/KGbHVKyWrqigzet39",
    category: "Date Night",
    description: "Nigeria's first cave-themed restaurant. Very dark and moody, built for Instagram photos.",
    menuHighlights: ["Cave Steak", "Turkish Kebab", "Hummus"],
  },
  {
    id: 21,
    name: "Terra Kulture",
    type: "Island",
    area: "VI",
    price: "₦8,000",
    image: "/images/terra-kulture.jpg",
    mapUrl: "https://maps.app.goo.gl/PY1AVzji5EJxeby1A",
    category: "Cultural",
    description: "The ultimate cultural hub of Lagos. It features an art gallery, theater, and a restaurant serving authentic Nigerian dishes.",
    menuHighlights: ["Ofada Rice", "Catfish Pepper Soup", "Palm Wine"],
  },
  {
    id: 22,
    name: "Eric Kayser",
    type: "Island",
    area: "VI",
    price: "₦12,000",
    image: "/images/eric-kayser.jpg",
    mapUrl: "https://maps.app.goo.gl/qm241jUU8KFKmUoz6",
    category: "Chill",
    description: "A French artisanal bakery and bistro. The perfect spot for a quiet breakfast, brunch, or a coffee date.",
    menuHighlights: ["Croissant", "Club Sandwich", "Gelato"],
  },
  {
    id: 23,
    name: "Yellow Chilli",
    type: "Island",
    area: "VI",
    price: "₦15,000",
    image: "/images/yellow-chilli.jpg",
    mapUrl: "https://maps.app.goo.gl/WqRQWTRXMrVG42GTA",
    category: "Cultural",
    description: "Upscale Nigerian dining. They take local dishes and present them with a modern, classy twist.",
    menuHighlights: ["Seafood Okra", "Jollof Fiesta", "Prawns"],
  },
  {
    id: 24,
    name: "Jevinik Place",
    type: "Island",
    area: "VI",
    price: "₦8,000",
    image: "/images/jevinik.jpg",
    mapUrl: "https://maps.app.goo.gl/7jsqfPS1ELyrb1tp9",
    category: "Budget Eats",
    description: "Legendary for its massive portions. If you want heavy traditional soups and swallow, this is the place.",
    menuHighlights: ["Afang Soup", "Fisherman Soup", "Abacha"],
  },
  {
    id: 25,
    name: "Mood Lagos",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦20,000",
    image: "/images/mood-lagos.jpg",
    mapUrl: "https://maps.app.goo.gl/fwmYq5cZU48VUsYg7",
    category: "Late Night",
    description: "A trendy rooftop lounge with great aesthetics. It gets very lively at night with DJ sets and a young crowd.",
    menuHighlights: ["Lamb Chops", "Signature Cocktails", "Pasta"],
  },
  {
    id: 26,
    name: "Bukka Hut",
    type: "Mainland",
    area: "Yaba",
    price: "₦4,000",
    image: "/images/bukka-hut.jpg",
    mapUrl: "https://maps.app.goo.gl/ZQzjE9rhh56rCrvSA",
    category: "Budget Eats",
    description: "The elevated 'Mama Put' experience. Fast, delicious, and very affordable traditional meals.",
    menuHighlights: ["Amala & Ewedu", "Beans & Plantain", "Goat Meat"],
  },
  {
    id: 27,
    name: "Godaif Village",
    type: "Island",
    area: "Ikoyi",
    price: "₦15,000",
    image: "/images/godaif.jpg",
    mapUrl: "https://maps.app.goo.gl/oQzvWxSyuTnzYQvT8",
    category: "Chill",
    description: "A massive garden space in Ikoyi with a play area for kids and a serene atmosphere for adults.",
    menuHighlights: ["Pizza", "Greek Salad", "Ginger Lemonade"],
  },
  {
    id: 28,
    name: "Stories Lagos",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦15,000",
    image: "/images/stories-lagos.jpg",
    mapUrl: "https://maps.app.goo.gl/gBkbi6m2koanG7jv5",
    category: "Chill",
    description: "A very social spot, great for group hangouts and pre-drinks. The decor is modern and very instagrammable.",
    menuHighlights: ["Wings Platter", "Sliders", "Mocktails"],
  },
  {
    id: 29,
    name: "La Taverna",
    type: "Island",
    area: "VI",
    price: "₦12,000",
    image: "/images/la-taverna.jpg",
    mapUrl: "https://maps.app.goo.gl/68VgWgRbJX6xKrLQ9",
    category: "Budget Eats",
    description: "Cozy Chilean & Italian restaurant. Famous for their Wednesday Pizza Night deals and friendly vibe.",
    menuHighlights: ["Thin Crust Pizza", "Empanadas", "Pasta"],
  },
  {
    id: 30,
    name: "So Fresh",
    type: "Mainland",
    area: "Yaba",
    price: "₦6,000",
    image: "/images/so-fresh.jpg",
    mapUrl: "https://maps.app.goo.gl/kDW68dKEQv8wXWfF8",
    category: "Health",
    description: "The healthiest spot on the list. Perfect for a quick lunch when you want salads, juices, or parfaits.",
    menuHighlights: ["Chicken Caesar Salad", "Green Smoothie", "Fruit Parfait"],
  },
  {
    id: 31,
    name: "Nike Art Gallery",
    type: "Island",
    area: "Lekki Phase 1",
    price: "Free",
    image: "/images/nike-art.jpg",
    mapUrl: "https://maps.app.goo.gl/45pX44jWrTrPSgxu7",
    category: "Cultural",
    description: "West Africa's largest art gallery. A four-story building filled with thousands of Nigerian artworks. You might even meet Mama Nike herself!",
    menuHighlights: ["Art Tours", "Cultural Dance", "Souvenirs"],
  },
  {
    id: 32,
    name: "RSVP",
    type: "Island",
    area: "VI",
    price: "₦100,000",
    image: "/images/rsvp.jpg",
    mapUrl: "https://maps.app.goo.gl/3QgkS59gzKvsFMXz5",
    category: "Date Night",
    description: "Minimalist, upscale New American restaurant. It has a poolside bar and is known for attracting a very stylish crowd.",
    menuHighlights: ["Chicken Sandwich", "Truffle Fries", "Craft Cocktails"],
  },
  {
    id: 33,
    name: "The House",
    type: "Island",
    area: "VI",
    price: "₦20,000",
    image: "/images/the-house.jpg",
    mapUrl: "https://maps.app.goo.gl/fwzc4BBurQkdVzak9",
    category: "Chill",
    description: "A social dining space designed to feel like a home. Each room has a different vibe (Library, Living Room, etc.).",
    menuHighlights: ["Seafood Pasta", "Sliders", "Chapman"],
  },
  {
    id: 34,
    name: "Lekki Conservation Centre",
    type: "Island",
    area: "Lekki",
    price: "₦3,000",
    image: "/images/lcc.jpg",
    mapUrl: "https://maps.app.goo.gl/PyWZKKe6k4kRbtPH7",
    category: "Activity",
    description: "Home to the longest canopy walkway in Africa. A great nature escape where you can see monkeys and play giant chess.",
    menuHighlights: ["Canopy Walk", "Coconut Water", "Picnic Snacks"],
  },
  {
    id: 35,
    name: "355 Restaurant & Lounge",
    type: "Mainland",
    area: "Ikeja",
    price: "₦25,000",
    image: "/images/355-ikeja.jpg",
    mapUrl: "https://maps.app.goo.gl/LFhm7AZPwL6YJDi5A",
    category: "Late Night",
    description: "Mexican fusion restaurant that turns into a club vibe at night. Great margaritas and energy.",
    menuHighlights: ["Beef Tacos", "Quesadillas", "Frozen Margaritas"],
  },
  {
    id: 36,
    name: "Iyeru Okin",
    type: "Mainland",
    area: "Ikeja",
    price: "₦3,500",
    image: "/images/iyeru-okin.jpg",
    mapUrl: "https://maps.app.goo.gl/CTjyGgDNnzHDSZNMA",
    category: "Budget Eats",
    description: "A beloved local spot for authentic Yoruba dishes. It's no-frills, fast, and the Amala is legendary.",
    menuHighlights: ["Amala & Gbegiri", "Assorted Meat", "Ponmo"],
  },
  {
    id: 37,
    name: "Crust & Cream",
    type: "Island",
    area: "VI",
    price: "₦15,000",
    image: "/images/crust-and-cream.jpg",
    mapUrl: "https://maps.app.goo.gl/yKZRjQzoJmJbBBVw8",
    category: "Chill",
    description: "A full-service bakery and bistro. A quiet spot perfect for working on your laptop or a casual business lunch.",
    menuHighlights: ["English Breakfast", "Red Velvet Cake", "Caesar Salad"],
  },
  {
    id: 38,
    name: "Landmark Beach",
    type: "Island",
    area: "VI",
    price: "₦4,000",
    image: "/images/landmark-beach.jpg",
    mapUrl: "https://maps.app.goo.gl/UR58P63oDdsRocjg6",
    category: "Activity",
    description: "The most popular private beach in Lagos. It features beach clubs, jet skis, and plenty of food vendors.",
    menuHighlights: ["Grilled Fish", "Beach Cocktails", "Suya"],
  },
  {
    id: 39,
    name: "La Giara",
    type: "Mainland",
    area: "Ikeja",
    price: "₦22,000",
    image: "/images/la-giara.jpg",
    mapUrl: "https://maps.app.goo.gl/1iU4RhD2SG15vB7r7",
    category: "Date Night",
    description: "Classic Italian dining located inside the Sheraton Hotel. Very quiet, old-school luxury.",
    menuHighlights: ["Lasagna", "Pizza", "Tiramisu"],
  },
  {
    id: 40,
    name: "Sooyah Bistro",
    type: "Mainland",
    area: "Yaba",
    price: "₦6,000",
    image: "/images/sooyah-bistro.jpg",
    mapUrl: "https://maps.app.goo.gl/PiqjPiCojBGBzTbKA",
    category: "Budget Eats",
    description: "Suya fusion. They take Nigerian street food and turn it into gourmet burgers and platters.",
    menuHighlights: ["Suya Burger", "Yam Fries", "Suya Melt"],
  },
  {
    id: 41,
    name: "NOK by Alara",
    type: "Island",
    area: "VI",
    price: "₦30,000",
    image: "/images/nok-by-alara.jpg",
    mapUrl: "https://maps.app.goo.gl/eyYEDoBNprNXUenA6",
    category: "Cultural",
    description: "Contemporary African dining set in a stunning architectural garden. It reinvents local classics for a fine-dining experience.",
    menuHighlights: ["Oxtail with Rice", "Abula", "Hibiscus Cocktail"],
  },
  {
    id: 42,
    name: "Cilantro",
    type: "Island",
    area: "VI",
    price: "₦30,000",
    image: "/images/cilantro-vi.jpg",
    mapUrl: "https://maps.app.goo.gl/GfG5aSzzgQvGNmb76",
    category: "Date Night",
    description: "Famous for its beautiful outdoor garden and incredible Indian cuisine. A very peaceful escape from the Lagos noise.",
    menuHighlights: ["Butter Chicken", "Garlic Naan", "Mixed Grill Platter"], 
  },
  {
    id: 43,
    name: "SLoW",
    type: "Island",
    area: "VI",
    price: "₦100,000",
    image: "/images/slow-lagos.jpg",
    mapUrl: "https://maps.app.goo.gl/5cevSuTyMPPysuvH7",
    category: "Date Night",
    description: "One of the trendiest spots in Lagos with a lush 'jungle' aesthetic. Expensive, exclusive, and great for celebrity spotting.",
    menuHighlights: ["Duck Salad", "Tacos", "Signature Cocktails"], 
  },
  {
    id: 44,
    name: "Ocean Basket",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦22,000",
    image: "/images/ocean-basket.jpg",
    mapUrl: "https://maps.app.goo.gl/4ZCnRbgLVYHUvYyU9",
    category: "Date Night",
    description: "The most reliable seafood chain in Nigeria. Perfect for families or dates where you want consistent quality.",
    menuHighlights: ["Platter for Two", "Creamy Lemon Prawns", "Mediterranean Sushi"], 
  },
  {
    id: 45,
    name: "Ile Iyan by PODs",
    type: "Mainland",
    area: "Yaba",
    price: "₦20,000",
    image: "/images/ile-iyan.jpg",
    mapUrl: "https://maps.app.goo.gl/vX2zMsMPQGFgWUJL7",
    category: "Cultural",
    description: "A specialty spot dedicated to Pounded Yam (Iyan). The setting is modern, but the food is strictly traditional.",
    menuHighlights: ["Pounded Yam", "Egusi Soup", "Efo Riro"], 
  },
  {
    id: 46,
    name: "Gossip Kitchen & Bar",
    type: "Island",
    area: "Ikoyi",
    price: "₦50,000",
    image: "/images/gossip-kitchen.jpg",
    mapUrl: "https://maps.app.goo.gl/ELkyoC6msLjNC3uU8",
    category: "Chill",
    description: "A highly aesthetic spot with floral decor. Great for brunch pictures and a relaxed evening with friends.",
    menuHighlights: ["Gossip Burger", "Pasta", "Strawberry Mojito"],
  },
  {
    id: 47,
    name: "Alice Garden",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦30,000",
    image: "/images/alice-garden.jpg",
    mapUrl: "https://maps.app.goo.gl/w4imjDRVG4ncv5N66",
    category: "Date Night",
    description: "A lovely outdoor garden restaurant in Ikeja. It has a mix of Korean and Continental vibes and is very spacious.",
    menuHighlights: ["Bulgogi", "Chicken Wings", "Chapman"], 
  },
  {
    id: 48,
    name: "Maple Lagos",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦50,000",
    image: "/images/maple-lagos.jpg",
    mapUrl: "https://maps.app.goo.gl/T3TbVDTnj4MgXnVN6",
    category: "Chill",
    description: "New York-style bistro famous for its brunch menu and chic interior. A top choice for Sunday dates.",
    menuHighlights: ["Chicken & Waffles", "Short Ribs", "Mimosas"], 
  },
  {
    id: 49,
    name: "Bungalow Restaurant",
    type: "Mainland",
    area: "Ikeja",
    price: "₦30,000",
    image: "/images/bungalow-ikeja.jpg",
    mapUrl: "https://maps.app.goo.gl/i7GDSbTdSiFmGy1c7",
    category: "Chill",
    description: "A diverse spot serving everything from Mexican to Japanese. Famous for their live Teppanyaki shows.",
    menuHighlights: ["Teppanyaki", "Sushi Platter", "Quesadillas"],
  },
  {
    id: 50,
    name: "Elysium Lagos",
    type: "Island",
    area: "Lekki",
    price: "₦18,000",
    image: "/images/elysium.jpg",
    mapUrl: "https://maps.app.goo.gl/YF8c81xkUNhtsYgB8",
    category: "Late Night",
    description: "A vibrant lounge and restaurant. Good for groups who want to eat well and then dance afterwards.",
    menuHighlights: ["Grill Platter", "Seafood Pasta", "Cocktails"], 
  },
  {
    id: 51,
    name: "Zen Garden",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦40,000",
    image: "/images/zen-garden.jpg",
    mapUrl: "https://maps.app.goo.gl/WRYVZZBgjC9HQR94A",
    category: "Date Night",
    description: "Authentic Chinese cuisine set in a peaceful, garden-like environment. A quiet escape from the Ikeja noise.",
    menuHighlights: ["Spring Rolls", "Special Fried Rice", "Shredded Beef"],
  },
  {
    id: 52,
    name: "Firewood Jollof",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦5,000",
    image: "/images/firewood-lekki.jpg",
    mapUrl: "https://maps.app.goo.gl/EgF2kpbGp9NVgUbx5",
    category: "Budget Eats",
    description: "Famous for its signature 'Smokey Party Jollof'. A casual spot that tastes exactly like wedding food.",
    menuHighlights: ["Smokey Jollof", "Fried Plantain", "Peppered Chicken"],
  },
  {
    id: 53,
    name: "Talindo Steak House",
    type: "Island",
    area: "VI",
    price: "₦45,000",
    image: "/images/talindo.jpg",
    mapUrl: "https://maps.app.goo.gl/wY7HHYWqtQKWukST7",
    category: "Date Night",
    description: "A legendary establishment known for serving some of the best steaks in Lagos. Quiet, exclusive, and expensive.",
    menuHighlights: ["T-Bone Steak", "Chocolate Mousse", "House Wine"],
  },
  {
    id: 54,
    name: "The Side Bar by Miskay",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦20,000",
    image: "/images/miskay-sidebar.jpg",
    mapUrl: "https://maps.app.goo.gl/qHtmuqt2g48L7hok9",
    category: "Chill",
    description: "A fashion-forward bistro with pink aesthetics. Very instagrammable and popular for girls' brunch.",
    menuHighlights: ["Beef Sliders", "Strawberry Daiquiri", "Waffles"],
  },
  {
    id: 55,
    name: "La Bamba",
    type: "Mainland",
    area: "Ikeja",
    price: "₦20,000",
    image: "/images/la-bamba.jpg",
    mapUrl: "https://maps.app.goo.gl/vCcs93JQxu69cT7YA",
    category: "Chill",
    description: "A relaxed lounge vibe with good music. Great for unwinding after work with colleagues.",
    menuHighlights: ["Peppered Snail", "Chapman", "Jollof Rice"],
  },
  {
    id: 56,
    name: "The Grill by Yanna",
    type: "Island",
    area: "Ikoyi",
    price: "₦25,000",
    image: "/images/grill-by-yanna.jpg",
    mapUrl: "https://maps.app.goo.gl/rjUBgr5uzHLVGmqz9",
    category: "Date Night",
    description: "An intimate outdoor grill space. It feels very private and serves excellent grilled meats and seafood.",
    menuHighlights: ["Ribeye Steak", "Mashed Potatoes", "Grilled Prawns"],
  },
  {
    id: 57,
    name: "Eatalia",
    type: "Mainland",
    area: "Yaba",
    price: "₦5,000",
    image: "/images/eatalia.jpg",
    mapUrl: "https://maps.app.goo.gl/FBEG5yRwnWDXDbQ16",
    category: "Budget Eats",
    description: "Budget-friendly Italian-Nigerian fusion. A student favorite for affordable pizza and pasta.",
    menuHighlights: ["Pepperoni Pizza", "Chicken Pasta", "Garlic Bread"],
  },
  {
    id: 58,
    name: "Noir Lagos",
    type: "Island",
    area: "VI",
    price: "₦35,000",
    image: "/images/noir.jpg",
    mapUrl: "https://maps.app.goo.gl/cJgu9RkQ7ACbAKsGA",
    category: "Date Night",
    description: "Modern French-inspired dining. The interior is dark and elegant (hence the name 'Noir'), perfect for romance.",
    menuHighlights: ["Escargot", "Steak Frites", "Fine Wine"], 
  },
  {
    id: 59,
    name: "Red Pepper",
    type: "Mainland",
    area: "Ikeja",
    price: "₦8,000",
    image: "/images/red-pepper.jpg",
    mapUrl: "https://maps.app.goo.gl/BmUowekWmVJ4roxu6",
    category: "Cultural",
    description: "A traditional spot specializing in African delicacies. The setting is simple, but the flavors are authentic.",
    menuHighlights: ["Isiewu", "Nkwobi", "Palm Wine"],
  },
  {
    id: 60,
    name: "Brass & Copper",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦16,000",
    image: "/images/brass-copper.jpg",
    mapUrl: "https://maps.app.goo.gl/aj3y72nZkqQMprWq7",
    category: "Chill",
    description: "A stylish spot known for its shisha lounge and brunch menu. The decor features distinct copper tones.",
   menuHighlights: ["Full English Breakfast", "Burgers", "Shisha"], 
  },
  {
    id: 61,
    name: "Kingfisher Africa",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦20,000",
    image: "/images/kingfisher.jpg",
    mapUrl: "https://maps.app.goo.gl/QEgN2Lt92ABvKqy29",
    category: "Late Night",
    description: "A waterfront restaurant perfect for evening drinks. The view of the Lekki-Ikoyi bridge at night is spectacular.",
    menuHighlights: ["Seafood Platter", "Kingfisher Cocktail", "Grilled Croaker"],
  },
  {
    id: 62,
    name: "Hello Suya",
    type: "Mainland",
    area: "Yaba",
    price: "₦4,500",
    image: "/images/hello-suya.jpg",
    mapUrl: "https://maps.app.goo.gl/iDEGUFhmKLnrAZHJA",
    category: "Late Night",
    description: "A modern take on the traditional suya spot. It's clean, well-branded, and serves spicy grilled meats late into the night.",
    menuHighlights: ["Beef Suya", "Chicken Suya", "Massai Burger"],
  },
  {
    id: 63,
    name: "La Veranda",
    type: "Island",
    area: "VI",
    price: "₦18,000",
    image: "/images/la-veranda.jpg",
    mapUrl: "https://maps.app.goo.gl/prCUyUY2JVWweai18",
    category: "Date Night",
    description: "Located inside The Blowfish Hotel, this is one of the best Italian spots in Lagos. Great for a quiet, romantic dinner.",
    menuHighlights: ["Wood-fired Pizza", "Tagliatelle Bolognese", "Tiramisu"],
  },
  {
    id: 64,
    name: "Commint Buka",
    type: "Mainland",
    area: "Surulere",
    price: "₦3,000",
    image: "/images/commint-buka.jpg",
    mapUrl: "https://maps.app.goo.gl/qqNPz8MkUm9e5DFS8",
    category: "Budget Eats",
    description: "A household name in Ikeja for authentic local food. It's always crowded because the food tastes like home cooking.",
    menuHighlights: ["Amala & Ewedu", "Moi Moi", "Fried Meat"],
  },
  {
    id: 65,
    name: "Golden Gate Restaurant",
    type: "Island",
    area: "Ikoyi",
    price: "₦20,000",
    image: "/images/golden-gate.jpg",
    mapUrl: "https://maps.app.goo.gl/PFbSZryJe5Mm2TuK6",
    category: "Cultural",
    description: "An iconic multi-story building in Ikoyi serving classic Chinese and Japanese cuisine. Great for large group dinners.",
    menuHighlights: ["Dim Sum", "Special Fried Rice", "Sweet & Sour Chicken"],
  },
 
  {
    id: 67,
    name: "Maroccaine",
    type: "Island",
    area: "VI",
    price: "₦12,000",
    image: "/images/maroccaine.jpg",
    mapUrl: "https://maps.app.goo.gl/tFNiwaoNULAaygvN7",
    category: "Late Night",
    description: "The spot that never sleeps. Famous for its massive menu and staying open very late. The vibe is casual and energetic.",
    menuHighlights: ["Pizza", "Seafood Pasta", "Shawarma"],
  },
  {
    id: 68,
    name: "Gidi Burger",
    type: "Mainland",
    area: "Surulere",
    price: "₦5,000",
    image: "/images/gidi-burger.jpg",
    mapUrl: "https://maps.app.goo.gl/pvHJE1DHaUPSpfxs6",
    category: "Budget Eats",
    description: "A dedicated burger joint on the Mainland. Known for juicy patties and generous portions of fries.",
    menuHighlights: ["Double Cheeseburger", "Loaded Fries", "Milkshake"],
  },
  {
    id: 69,
    name: "Rukash Restaurant",
    type: "Mainland",
    area: "Ikeja",
    price: "₦10,000",
    image: "/images/rukash.jpg",
    mapUrl: "https://maps.app.goo.gl/kHQY3ufYxLisJdyQ8",
    category: "Chill",
    description: "A relaxed lounge and grill spot in Ikeja. Good for watching football matches and enjoying grilled food.",
    menuHighlights: ["Grilled Catfish", "Pepper Soup", "Cold Beer"],
  },
  {
    id: 70,
    name: "234 Restaurant",
    type: "Island",
    area: "Lekki",
    price: "₦18,000",
    image: "/images/234-restaurant.jpg",
    mapUrl: "https://maps.app.goo.gl/tpUiAPD9hQsK9aa57",
    category: "Cultural",
    description: "A fusion spot celebrating Nigerian flavors. The setting is modern African and the food is consistently good.",
    menuHighlights: ["Jollof Rice with Turkey", "Plantain Platter", "Zobo Cocktail"],
  },
  {
    id: 71,
    name: "Sketch Restaurant",
    type: "Island",
    area: "VI",
    price: "₦25,000",
    image: "/images/sketch-lagos.jpg",
    mapUrl: "https://maps.app.goo.gl/jT4p5tyi7ZXF352h8",
    category: "Activity",
    description: "Africa's first 2D/3D restaurant. The entire interior looks like a black-and-white comic book drawing. Incredible for photos.",
    menuHighlights: ["Sketch Burger", "Pasta Carbonara", "Milkshakes"],
  },
  {
    id: 72,
    name: "Turaka Lagos",
    type: "Island",
    area: "VI",
    price: "₦20,000",
    image: "/images/turaka.jpg",
    mapUrl: "https://maps.app.goo.gl/bte7GyoJT28yPatN6",
    category: "Chill",
    description: "A rooftop restaurant at the EbonyLife Place offering stunning views of Victoria Island. Great for breezy evening drinks.",
    menuHighlights: ["Goat Meat Sliders", "Turaka Platter", "Chapman"],
  },
  {
    id: 73,
    name: "Essence By The Grid",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦25,000",
    image: "/images/essence-grid.jpg",
    mapUrl: "https://maps.app.goo.gl/ue1oiTwvMenJc6cn9",
    category: "Date Night",
    description: "The upscale sibling of The Grid. It offers a more refined fine-dining experience with elegant decor.",
    menuHighlights: ["Lamb Chops", "Seafood Paella", "Red Wine"],
  },
  {
    id: 74,
    name: "Terraform Bar & Restaurant",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦40,000",
    image: "/images/terraform.jpg",
    mapUrl: "https://maps.app.goo.gl/nXAYiPZabPJ597YG8",
    category: "Chill",
    description: "A massive waterfront space in Lekki. It has an upper deck with a great view and is very spacious for large groups.",
    menuHighlights: ["Grilled Fish", "Buffalo Wings", "Long Island Tea"],
  },
  {
    id: 75,
    name: "Casper & Gambini",
    type: "Mainland",
    area: "Ikeja",
    price: "₦25,000",
    image: "/images/casper-gambini.jpg",
    mapUrl: "https://maps.app.goo.gl/XSceU1UQtGbKEKNAA",
    category: "Date Night",
    description: "An international franchise known for high-quality continental food. The setting is polished and perfect for business meetings or dates.",
    menuHighlights: ["Club Sandwich", "Gambini Burger", "Iced Latte"],
  },
  {
    id: 76,
    name: "JustAfang",
    type: "Island",
    area: "Ikoyi",
    price: "₦10,000",
    image: "/images/just-afang.jpg",
    mapUrl: "https://maps.app.goo.gl/57NS9J3WvU4NVb7r8",
    category: "Cultural",
    description: "Specializes in delicacies from South-South Nigeria. As the name suggests, their Afang soup is the star of the show.",
    menuHighlights: ["Afang Soup", "Edikang Ikong", "Pounded Yam"],
  },
  {
    id: 77,
    name: "Ox Restaurant",
    type: "Island",
    area: "VI",
    price: "₦35,000",
    image: "/images/ox-restaurant.jpg",
    mapUrl: "https://maps.app.goo.gl/kxUuiSdbHuDuXXhH6",
    category: "Late Night",
    description: "A dark, moody lounge with a distinct Nordic theme. It turns into a high-energy vibe spot late at night.",
    menuHighlights: ["Steak", "Ox Platter", "Signature Cocktails"],
  },
  {
    id: 78,
    name: "Bamboo Lounge",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦10,000",
    image: "/images/bamboo-lounge.jpg",
    mapUrl: "https://maps.app.goo.gl/tX45oWbJJoXeiZUT8",
    category: "Chill",
    description: "A relaxed outdoor spot with a tropical theme. Good for casual drinks and catching up with friends.",
    menuHighlights: ["Peppered Snail", "BBQ Chicken", "Beer"],
  },
  {
    id: 79,
    name: "Primi Piatti",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦22,000",
    image: "/images/primi-piatti.jpg",
    mapUrl: "https://maps.app.goo.gl/KWk7XU9kSSW4cvp66",
    category: "Date Night",
    description: "An Italian restaurant with a beautiful deck overlooking the water. One of the more romantic spots in Lekki.",
    menuHighlights: ["Seafood Pasta", "Pizza", "Gelato"],
  },
  {
    id: 80,
    name: "Kulture Yard",
    type: "Mainland",
    area: "Ikeja",
    price: "₦6,000",
    image: "/images/kulture-yard.jpg",
    mapUrl: "https://maps.app.goo.gl/1jaoVkmZfYqyGgHe9",
    category: "Chill",
    description: "A cool, artsy space on the mainland. They often host live bands, open mic nights, and cultural events.",
    menuHighlights: ["Suya", "Noodles", "Palm Wine"],
  },
  {
    id: 81,
    name: "Upbeat Centre",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦10,000",
    image: "/images/upbeat.jpg",
    mapUrl: "https://maps.app.goo.gl/uprCmW4Mc96EUgiHA",
    category: "Activity",
    description: "West Africa's first trampoline park. It’s huge, energetic, and features dodgeball courts and foam pits. Great for dates or group fitness.",
    menuHighlights: ["Trampoline Jump", "Dodgeball", "Slushies"],
  },
  {
    id: 82,
    name: "JJT Park (Johnson Jakande Tinubu)",
    type: "Mainland",
    area: "Ikeja",
    price: "Free",
    image: "/images/jjt.jpg",
    mapUrl: "https://www.google.com/maps/place/Johnson+Jakande+Tinubu+(JJT)+Park/@6.6152499,3.3639417,3a,75y,90t/data=!3m8!1e2!3m6!1sCIHM0ogKEICAgIDsjuCBpAE!2e10!3e12!6shttps:%2F%2Flh3.googleusercontent.com%2Fgps-cs-s%2FAG0ilSzEnn1UiHbsTV9pVLTMxx-R1ASTtduBp9Xgv8R38OC12jB9AibE0qqbTjEvafdh8AaM2r8LjXM-DpwRnsK5qZOSrImE81Kqpt2Qdkj54I37_F7Lo9o5M6uGL0fFTjHL1_n7-3qd%3Dw114-h86-k-no!7i3264!8i2448!4m7!3m6!1s0x103b93b598785b33:0xa34c5b687075d120!8m2!3d6.6151813!4d3.3639417!10e5!16s%2Fg%2F11f3jjhnwl?coh=277535&entry=tt",
    category: "Activity",
    description: "A very clean and scenic public park in Alausa. It has free Wi-Fi, a giant chess board, and lush green grass for picnics.",
    menuHighlights: ["Picnic", "Giant Chess", "Waterfall Photos"],
  },
  {
    id: 83,
    name: "The Good Beach",
    type: "Island",
    area: "VI",
    price: "₦6,000",
    image: "/images/good-beach.jpg",
    mapUrl: "https://goo.gl/maps/change-me",
    category: "Activity",
    description: "A trendy beachfront club with a pool, cabanas, and very aesthetics vibes. It is cleaner and more organized than most public beaches.",
    menuHighlights: ["Beach Cabana", "Grilled Fish", "Cocktails"],
  },
  {
    id: 84,
    name: "Kalakuta Republic Museum",
    type: "Mainland",
    area: "Ikeja",
    price: "₦3,000",
    image: "/images/kalakuta.jpg",
    mapUrl: "https://maps.app.goo.gl/1H46Yb7EZGzSLJZ47",
    category: "Cultural",
    description: "The former home of Fela Kuti turned into a museum. You can see his bedroom, clothes, and shoes exactly as he left them.",
    menuHighlights: ["Museum Tour", "Rooftop Bar", "Fela Souvenirs"],
  },
  {
    id: 85,
    name: "Lufasi Nature Park",
    type: "Island",
    area: "Lekki",
    price: "₦2,000",
    image: "/images/lufasi.jpg",
    mapUrl: "https://maps.app.goo.gl/7fw2Hmq3UXKXE6Ku9",
    category: "Activity",
    description: "A forest conservation center. It is very quiet and peaceful, home to donkeys, monkeys, and beautiful nature trails.",
    menuHighlights: ["Nature Walk", "Table Tennis", "Picnic"],
  },
  {
    id: 86,
    name: "New Afrika Shrine",
    type: "Mainland",
    area: "Ikeja",
    price: "₦3,000",
    image: "/images/shrine.jpg",
    mapUrl: "https://maps.app.goo.gl/VJL4Q1q9JRCA99c19",
    category: "Cultural",
    description: "The spiritual home of Afrobeat. Expect loud live music, energetic dancing, and a raw, authentic Lagos energy.",
    menuHighlights: ["Live Afrobeat", "Palm Wine", "Suya"],
  },
  {
    id: 87,
    name: "Sol Beach Elegushi by Boxmall",
    type: "Island",
    area: "VI",
    price: "₦5,000",
    image: "/images/sol-beach.jpg",
    mapUrl: "https://maps.app.goo.gl/mr9cv9gJAniqTxJq7",
    category: "Activity",
    description: "A popular private beach club known for its party vibes on weekends and chill atmosphere on weekdays.",
    menuHighlights: ["Beach Volleyball", "Grilled Turkey", "Tequila"],
  },
  {
    id: 88,
    name: "Ndubuisi Kanu Park",
    type: "Mainland",
    area: "Ikeja",
    price: "Free",
    image: "/images/ndubuisi-park.jpg",
    mapUrl: "https://maps.app.goo.gl/NQD8d1gEoLTKFikj6",
    category: "Activity",
    description: "A great public park in Ikeja. It has a basketball court, playground for kids, and plenty of space for reading or relaxing.",
    menuHighlights: ["Basketball", "Lawn Tennis", "Snacks"],
  },
  {
    id: 89,
    name: "Lakowe Lakes",
    type: "Island",
    area: "Lakowe",
    price: "₦30,000",
    image: "/images/lakowe.jpg",
    mapUrl: "https://maps.app.goo.gl/2p7SgMZ6aKyGFqjz6",
    category: "Activity",
    description: "A luxury golf resort and estate. It feels like you have left Nigeria. Perfect for a weekend getaway or a golfing day trip.",
    menuHighlights: ["Golfing", "Pedal Boats", "Fine Dining"],
  },
  {
    id: 90,
    name: "Freedom Park",
    type: "Island",
    area: "Lagos Island",
    price: "₦1,000",
    image: "/images/freedom-park.jpg",
    mapUrl: "https://maps.app.goo.gl/qa7rzDBfGbc9cSDF6",
    category: "Cultural",
    description: "A former colonial prison turned into a leisure park. It hosts many concerts, theater performances, and art exhibitions.",
    menuHighlights: ["Museum Cells", "Live Stage", "Fish & Chips"],
  },
  {
    id: 91,
    name: "Taj Restaurant",
    type: "Island",
    area: "VI",
    price: "₦50,000",
    image: "/images/taj-restaurant.jpg",
    mapUrl: "https://maps.app.goo.gl/iLpN2G5dXqevUUCr5",
    category: "Date Night",
    description: "Upscale Indian fine dining. The decor is regal and elegant, and the curry is arguably the best on the Island.",
    menuHighlights: ["Lamb Rogan Josh", "Butter Naan", "Mango Lassi"],
  },
  {
    id: 92,
    name: "The Station",
    type: "Island",
    area: "Ikoyi",
    price: "₦12,000",
    image: "/images/the-station.jpg",
    mapUrl: "https://maps.app.goo.gl/Kqaxz1H8DfHLVf6B6",
    category: "Chill",
    description: "A relaxed spot near the water. It’s unpretentious, breezy, and great for a casual beer and burger evening.",
    menuHighlights: ["Stir Fry", "Chicken Wings", "Jollof Rice"],
  },
  {
    id: 93,
    name: "Foodies Hot and Spicy",
    type: "Island",
    area: "Lekki",
    price: "₦4,000",
    image: "/images/foodies-lekki.jpg",
    mapUrl: "https://maps.app.goo.gl/5GJi25NySihJJjdJA",
    category: "Budget Eats",
    description: "A very popular fast-food style restaurant. It’s clean, fast, and serves a massive variety of Nigerian dishes buffet-style.",
    menuHighlights: ["Jollof Rice", "Fried Rice", "Coleslaw"],
  },
  {
    id: 94,
    name: "Oshey Bar & Chops",
    type: "Mainland",
    area: "Yaba",
    price: "₦3,500",
    image: "/images/oshey-bar.jpg",
    mapUrl: "https://maps.app.goo.gl/e98EvDpYTrfE2MJz7",
    category: "Late Night",
    description: "A proper local hangout spot on the Mainland. Loud music, cold drinks, and spicy small chops. Very energetic.",
    menuHighlights: ["Small Chops", "Asun", "Beer"],
  },
  {
    id: 95,
    name: "Gaby Lagos",
    type: "Island",
    area: "VI",
    price: "₦30,000",
    image: "/images/gaby-lagos.jpg",
    mapUrl: "https://maps.app.goo.gl/fNLmW8AVz8G4ejxZ9",
    category: "Date Night",
    description: "A Mediterranean fusion restaurant with a theatrical flair. The interior design is bold and artistic.",
    menuHighlights: ["Seafood Paella", "Steak", "Signature Cocktails"],
  },
  {
    id: 96,
    name: "The B-Hive",
    type: "Island",
    area: "Ikoyi",
    price: "₦8,000",
    image: "/images/b-hive.jpg",
    mapUrl: "https://maps.app.goo.gl/QtpDfo2x1pAqXx4K7",
    category: "Chill",
    description: "A cozy bakery and cafe. One of the best spots in Ikoyi for fresh pastries, donuts, and a quiet breakfast.",
    menuHighlights: ["Glazed Donuts", "Chicken Pie", "Cappuccino"],
  },
  {
    id: 97,
    name: "Kobis",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦4,000",
    image: "/images/kobis.jpg",
    mapUrl: "https://maps.app.goo.gl/EhefX7PUaXSwaJBCA",
    category: "Budget Eats",
    description: "A quick-service restaurant known for hygiene and tasty rice dishes. Great for a quick lunch break.",
    menuHighlights: ["Jollof Rice", "Moi Moi", "Fried Chicken"],
  },
  {
    id: 98,
    name: "Zoe’s Bistro",
    type: "Island",
    area: "Ikoyi",
    price: "₦15,000",
    image: "/images/zoes-bistro.jpg",
    mapUrl: "https://maps.app.goo.gl/8xrfRtMUik6yFudM9",
    category: "Chill",
    description: "A charming, vegetarian-friendly bistro. It feels like a small cottage and serves very fresh, healthy meals.",
    menuHighlights: ["Greek Salad", "Vegetarian Pasta", "Fresh Juice"],
  },
  {
    id: 99,
    name: "Mabaya Restaurant",
    type: "Island",
    area: "Lekki",
    price: "₦18,000",
    image: "/images/mabaya.jpg",
    mapUrl: "https://maps.app.goo.gl/RmycXGqLGbAhXkRM6",
    category: "Late Night",
    description: "A lounge setting that mixes dining with nightlife. The lighting is moody and the music is usually Afrobeats.",
    menuHighlights: ["Grill Platter", "Cocktails", "Spicy Prawns"],
  },
  {
    id: 100,
    name: "100 Hours",
    type: "Island",
    area: "Ikoyi",
    price: "₦15,000",
    image: "/images/100-hours.jpg",
    mapUrl: "https://maps.app.goo.gl/Qvm61FZnRoSsn3pP8",
    category: "Chill",
    description: "An outdoor lounge in Ikoyi suitable for relaxing after work. It’s spacious and rarely feels overcrowded.",
    menuHighlights: ["BBQ Fish", "Fries", "Cocktails"],
  },
  {
    id: 101,
    name: "Ile Eros",
    type: "Island",
    area: "Lekki Phase 1",
    price: "₦25,000",
    image: "/images/ile-eros.jpg",
    mapUrl: "https://maps.app.goo.gl/NEsocu78VcS9KEsv9",
    category: "Cultural",
    description: "Polished Nigerian fusion dining. They are famous for taking local ingredients and presenting them like 5-star fine dining.",
    menuHighlights: ["Jollof Rice & Plantain", "Pepper Soup", "Asun"],
  },
  {
    id: 102,
    name: "Vanilla Moon",
    type: "Island",
    area: "VI",
    price: "₦20,000",
    image: "/images/vanilla-moon.jpg",
    mapUrl: "https://maps.app.goo.gl/Wx9WHSfnwHfnZnrB6",
    category: "Date Night",
    description: "A beautiful spot for romantic dinners. The outdoor terrace is lovely, and they serve a mix of European and Pan-African dishes.",
    menuHighlights: ["Moon Breakfast", "Seafood Pasta", "Cocktails"],
  },
  {
    id: 103,
    name: "Soul Food",
    type: "Mainland",
    area: "Yaba",
    price: "₦7,000",
    image: "/images/soul-food.jpg",
    mapUrl: "https://maps.app.goo.gl/zNXDBCLuQhBiT3D6A",
    category: "Chill",
    description: "The aesthetic king of Yaba. Very popular with students and creatives for its pastel decor and creamy pasta.",
    menuHighlights: ["Creamy Pasta", "Waffles & Chicken", "Milkshakes"],
  },
  {
    id: 104,
    name: "Orchid House Thai",
    type: "Mainland",
    area: "Ikeja",
    price: "₦18,000",
    image: "/images/orchid-thai.jpg",
    mapUrl: "https://maps.app.goo.gl/X6znxsUbfE7ktzPb6",
    category: "Date Night",
    description: "Distinct from Orchid Bistro, this spot specializes in authentic Thai cuisine. A hidden gem for spicy food lovers in Ikeja.",
    menuHighlights: ["Pad Thai", "Green Curry", "Spring Rolls"],
  },
  {
    id: 105,
    name: "Labule",
    type: "Island",
    area: "Lekki",
    price: "₦4,000",
    image: "/images/labule.jpg",
    mapUrl: "https://maps.app.goo.gl/qGNHP6vNfZSXxq4B6",
    category: "Budget Eats",
    description: "Bringing the 'Buka' experience to the Island. It is clean, air-conditioned, but serves proper Amala and Gbegiri.",
    menuHighlights: ["Amala & Ewedu", "Moi Moi", "Fried Meat"],
  },
  {
    id: 106,
    name: "Prime Chinese",
    type: "Island",
    area: "Ikoyi",
    price: "₦20,000",
    image: "/images/prime-chinese.jpg",
    mapUrl: "https://maps.app.goo.gl/JMrr8AU3WEJCTCMn9",
    category: "Late Night",
    description: "Famous for being open 24/7 (or very late). It is the go-to spot for Chinese food after a night out of partying.",
    menuHighlights: ["Special Fried Rice", "Prawns in Chilli", "Spring Rolls"],
  },
  {
    id: 107,
    name: "The Vibe",
    type: "Island",
    area: "VI",
    price: "₦50,000",
    image: "/images/the-vibe.jpg",
    mapUrl: "https://maps.app.goo.gl/7xMRqBVS3CxGEHiR7",
    category: "Late Night",
    description: "A high-energy lounge perfect for Friday nights. It bridges the gap between a restaurant and a night club.",
    menuHighlights: ["Grill Platter", "Cocktails", "Shisha"],
  },
  {
    id: 108,
    name: "Nuli",
    type: "Island",
    area: "Ikoyi",
    price: "₦8,000",
    image: "/images/nuli-ikoyi.jpg",
    mapUrl: "https://maps.app.goo.gl/iqJeYq9R9ffbE6PT6",
    category: "Health",
    description: "The pioneer of healthy fast food in Lagos. The perfect spot for fresh juice, salads, and guilt-free meals.",
    menuHighlights: ["Chicken Caesar Salad", "Farm Fresh Juice", "Wraps"],
  },
  {
    id: 109,
    name: "Indomie Cafe",
    type: "Mainland",
    area: "Yaba",
    price: "₦3,500",
    image: "/images/indomie-cafe.jpg",
    mapUrl: "https://maps.app.goo.gl/rUDCbDCUsUL1W96G7",
    category: "Budget Eats",
    description: "A cult favorite. They take instant noodles and turn them into gourmet meals with eggs, sausages, and secret spices.",
    menuHighlights: ["Indomie & Egg", "Yoodles", "Fruit Juice"],
  },
  {
    id: 110,
    name: "Old English Bar",
    type: "Island",
    area: "Lekki",
    price: "₦10,000",
    image: "/images/old-english.jpg",
    mapUrl: "https://maps.app.goo.gl/bzAsLwm8Z4WdU4ba6",
    category: "Late Night",
    description: "A classic spot for music, grilled turkey, and drinks. It has a very loyal following among Lekki residents.",
    menuHighlights: ["Grilled Turkey", "Catfish", "Draft Beer"],
  },
  {
    id: 111,
    name: "University of Suya",
    type: "Mainland",
    area: "Ikeja",
    price: "₦3,000",
    image: "/images/university-suya.jpg",
    mapUrl: "https://maps.app.goo.gl/z2kj85Bg1k8zoSGk9",
    category: "Late Night",
    description: "Located on Allen Avenue, this is arguably the most famous Suya spot in Lagos. No degrees served here, just spicy grilled meat.",
    menuHighlights: ["Beef Suya", "Kidney", "Massai Special"],
  },
  {
    id: 112,
    name: "Olaiya Foods",
    type: "Mainland",
    area: "Surulere",
    price: "₦3,500",
    image: "/images/olaiya.jpg",
    mapUrl: "https://maps.app.goo.gl/mMBGBGwe1zLsjxQA7",
    category: "Budget Eats",
    description: "A legendary spot in Surulere famous for its Amala. The queue is always long, but the food is worth the wait.",
    menuHighlights: ["Amala & Gbegiri", "Goat Meat", "Ewedu"],
  },
  {
    id: 113,
    name: "Mega Chicken",
    type: "Mainland",
    area: "Ikeja",
    price: "₦6,000",
    image: "/images/mega-chicken.jpg",
    mapUrl: "https://maps.app.goo.gl/a35ZSLdFRcfi2D9X9",
    category: "Budget Eats",
    description: "A massive restaurant serving everything from Chinese fried rice to Swallow. It is a go-to for family outings on the Mainland.",
    menuHighlights: ["Chinese Fried Rice", "Rotisserie Chicken", "Swallow"],
  },
  {
    id: 114,
    name: "Amala Yahoo",
    type: "Mainland",
    area: "Ogudu",
    price: "₦3,000",
    image: "/images/amala-yahoo.jpg",
    mapUrl: "https://maps.app.goo.gl/H6WXH4We7MaKpEMp8",
    category: "Cultural",
    description: "A cult classic. It has no signboard, but everyone knows it. The Amala here is rumored to be addictive.",
    menuHighlights: ["Amala", "Assorted Meat", "Fresh Fish"],
  },
  {
    id: 115,
    name: "Rodizzio",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦15,000",
    image: "/images/rodizzio.jpg",
    mapUrl: "https://maps.app.goo.gl/abuzS4C8x3aFyj9y6",
    category: "Date Night",
    description: "A Brazilian-style steakhouse that also features Nigerian comedy nights. Great for meat lovers.",
    menuHighlights: ["Unlimited BBQ", "Jambalaya Rice", "Grilled Pineapple"],
  },
  {
    id: 116,
    name: "Poolside Restaurant, Sheraton Lagos Hotel",
    type: "Mainland",
    area: "Ikeja",
    price: "₦20,000",
    image: "/images/sheraton.jpg",
    mapUrl: "https://maps.app.goo.gl/Avv4xKyK7Lfs19Ge8",
    category: "Chill",
    description: "Located inside Sheraton Hotel. It features a live band, expensive drinks, and a very mature, relaxed crowd.",
    menuHighlights: ["Club Sandwich", "Draft Beer", "Peanut Burger"],
  },
  {
    id: 117,
    name: "Collage (Radisson Blu)",
    type: "Mainland",
    area: "Ikeja GRA",
    price: "₦25,000",
    image: "/images/collage.jpg",
    mapUrl: "https://maps.app.goo.gl/hEXLXWLJw5fMYYwm6",
    category: "Date Night",
    description: "A premium dining experience inside the Radisson Blu Hotel. [cite_start]Their Sunday Brunch buffet is legendary[cite: 214].",
    menuHighlights: ["Buffet", "Steak", "Dessert Bar"],
  },
 
];