export const locations = [
  // --- MAINLAND SPOTS ---
  {
    id: 1,
    name: "The Orchid Bistro",
    area: "Ikeja",
    type: "Mainland",
    price: "₦15,000",
    category: "Date Night",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=600",
    websiteUrl: "https://www.instagram.com/theorchidbistro",
    mapUrl: "https://goo.gl/maps/OrchidBistro",
    description: "A quaint bistro with a beautiful orchid garden. Perfect for romantic dates and quiet coffee meetings. Their breakfast menu is legendary in Ikeja."
  },
  {
    id: 2,
    name: "JJT Park (Johnson Jakande Tinubu)",
    area: "Alausa",
    type: "Mainland",
    price: "Free",
    category: "Hangout",
    image: "https://images.unsplash.com/photo-1563514227146-23961732e744?q=80&w=600",
    websiteUrl: "https://laspark.lg.gov.ng/",
    mapUrl: "https://goo.gl/maps/JJTPark",
    description: "One of the few high-quality green spaces in Lagos. Completely free to enter, featuring a fountain, free WiFi, and plenty of space for picnics."
  },
  {
    id: 5,
    name: "La Mango Restaurant",
    area: "Ikeja",
    type: "Mainland",
    price: "₦8,000",
    category: "Food & Drinks",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=80&w=600",
    websiteUrl: "https://www.instagram.com/lamangolagos",
    mapUrl: "https://goo.gl/maps/LaMango",
    description: "A classic Ikeja spot. Good for group hangouts, watching football matches, and enjoying affordable Nigerian jollof and pepper soup."
  },
  {
    id: 6,
    name: "Kalakuta Republic Museum",
    area: "Ikeja",
    type: "Mainland",
    price: "₦2,000",
    category: "Art & Culture",
    image: "https://images.unsplash.com/photo-1552018800-410a5628a58f?q=80&w=600",
    websiteUrl: "https://www.kalakutamuseum.com/",
    mapUrl: "https://goo.gl/maps/Kalakuta",
    description: "The former home of Fela Kuti. It is now a museum preserving his legacy. A must-visit for music lovers and history buffs."
  },
  {
    id: 7,
    name: "Rhapsody's Ikeja",
    area: "Ikeja City Mall",
    type: "Mainland",
    price: "₦18,000",
    category: "Date Night",
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=600",
    websiteUrl: "https://rhapsodys.com.ng/",
    mapUrl: "https://goo.gl/maps/Rhapsodys",
    description: "Located inside ICM, this is a top spot for Friday nights. Great cocktails, lively music, and a premium crowd without being too expensive."
  },
  {
    id: 8,
    name: "Grid Lagos",
    area: "Ikeja",
    type: "Mainland",
    price: "₦20,000",
    category: "Nightlife",
    image: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?q=80&w=600",
    websiteUrl: "https://www.instagram.com/gridlagos",
    mapUrl: "https://goo.gl/maps/GridLagos",
    description: "One of the swankiest spots on the Mainland. The decor is top-tier, making it perfect for birthday dinners and 'Mainland Big Boy' vibes."
  },
  {
    id: 9,
    name: "Ndubuisi Kanu Park",
    area: "Alausa",
    type: "Mainland",
    price: "Free",
    category: "Hangout",
    image: "https://images.unsplash.com/photo-1496347646636-ea47f7d6b37b?q=80&w=600",
    websiteUrl: "https://laspark.lg.gov.ng/",
    mapUrl: "https://goo.gl/maps/Ndubuisi",
    description: "A quiet, green park perfect for reading, basketball, or small picnics. Very secure and well-maintained by the state government."
  },
  {
    id: 10,
    name: "New Afrika Shrine",
    area: "Ikeja",
    type: "Mainland",
    price: "₦3,000",
    category: "Nightlife",
    image: "https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=600",
    websiteUrl: "https://www.instagram.com/afrikashrine",
    mapUrl: "https://goo.gl/maps/Shrine",
    description: "The heartbeat of Afrobeat. Visit on Thursday or Sunday nights for live performances. It is raw, energetic, and purely Lagos."
  },
  {
    id: 11,
    name: "Purple Bistro",
    area: "Yaba",
    type: "Mainland",
    price: "₦7,000",
    category: "Food",
    image: "https://images.unsplash.com/photo-1550966871-3ed3c47e2ce2?q=80&w=600",
    websiteUrl: "https://www.instagram.com/purplebistro",
    mapUrl: "https://goo.gl/maps/PurpleBistro",
    description: "A student favorite near UNILAG. Very affordable pasta and burgers. Small space but big flavors."
  },
  {
    id: 12,
    name: "Hi-Impact Planet",
    area: "Outskirts",
    type: "Mainland",
    price: "₦10,000",
    category: "Activity",
    image: "https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?q=80&w=600",
    websiteUrl: "https://hi-impactplanet.com/",
    mapUrl: "https://goo.gl/maps/HiImpact",
    description: "A full amusement park with roller coasters and arcade games. It is a bit of a drive, but worth it for a full day of fun."
  },

  // --- ISLAND SPOTS ---
  {
    id: 3,
    name: "Nike Art Gallery",
    area: "Lekki Phase 1",
    type: "Island",
    price: "Free",
    category: "Art & Culture",
    image: "https://images.unsplash.com/photo-1544967082-d9d3fdd01a1d?q=80&w=600",
    websiteUrl: "https://nikeart.com/",
    mapUrl: "https://goo.gl/maps/NikeArt",
    description: "West Africa's largest art gallery. A 4-story building filled with breathtaking Nigerian art. You might even meet Mama Nike herself!"
  },
  {
    id: 4,
    name: "Danfo Bistro",
    area: "Ikoyi",
    type: "Island",
    price: "₦12,000",
    category: "Food",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?q=80&w=600",
    websiteUrl: "https://www.instagram.com/danfobistro",
    mapUrl: "https://goo.gl/maps/DanfoBistro",
    description: "Street food elevated to fine dining. Their Ewa Agoyin sandwich is a must-try. The decor is inspired by the iconic yellow buses of Lagos."
  },
  {
    id: 13,
    name: "Lekki Conservation Centre",
    area: "Lekki",
    type: "Island",
    price: "₦5,000",
    category: "Activity",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=600",
    websiteUrl: "https://ncfnigeria.org/lekki-conservation-centre",
    mapUrl: "https://goo.gl/maps/LCC",
    description: "Home to the longest canopy walk in Africa. See monkeys, peacocks, and enjoy nature. Warning: The monkeys will steal your snacks!"
  },
  {
    id: 14,
    name: "Rufus & Bee",
    area: "Lekki (Twinwaters)",
    type: "Island",
    price: "₦15,000",
    category: "Activity",
    image: "https://images.unsplash.com/photo-1511882150382-421056ac8d89?q=80&w=600",
    websiteUrl: "https://www.twinwaterslagos.com/rufus-bee",
    mapUrl: "https://goo.gl/maps/RufusBee",
    description: "The ultimate arcade center in Lagos. Bowling, video games, and sports viewing. Great for groups and first dates."
  },
  {
    id: 15,
    name: "Terra Kulture",
    area: "Victoria Island",
    type: "Island",
    price: "₦5,000",
    category: "Art & Culture",
    image: "https://images.unsplash.com/photo-1499364615650-ec38552f4f34?q=80&w=600",
    websiteUrl: "https://terrakulture.com/",
    mapUrl: "https://goo.gl/maps/Terra",
    description: "A cultural hub featuring a restaurant, art gallery, and theater. Their Nigerian food is authentic and the plays are world-class."
  },
  {
    id: 16,
    name: "Landmark Beach",
    area: "Victoria Island",
    type: "Island",
    price: "₦3,500",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=600",
    websiteUrl: "https://www.landmarkbeach.ng/",
    mapUrl: "https://goo.gl/maps/Landmark",
    description: "The most organized beach in Lagos. Clean sand, boardwalks, and plenty of food vendors. Great for jogging or just relaxing."
  },
  {
    id: 17,
    name: "The Good Beach",
    area: "Victoria Island",
    type: "Island",
    price: "₦4,000",
    category: "Beach",
    image: "https://images.unsplash.com/photo-1520483602335-3b3dd1c2c071?q=80&w=600",
    websiteUrl: "https://www.thegoodbeachlagos.com/",
    mapUrl: "https://goo.gl/maps/GoodBeach",
    description: "A stylish, younger vibe compared to Landmark. The aesthetics are very 'Instagrammable' with a lovely pool area."
  },
  {
    id: 18,
    name: "Hard Rock Cafe",
    area: "Victoria Island",
    type: "Island",
    price: "₦25,000",
    category: "Nightlife",
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?q=80&w=600",
    websiteUrl: "https://www.hardrockcafe.com/location/lagos/",
    mapUrl: "https://goo.gl/maps/HardRock",
    description: "International standard burgers and drinks. Live bands perform often, and the beachfront view is stunning at night."
  },
  {
    id: 19,
    name: "Art Cafe",
    area: "Victoria Island",
    type: "Island",
    price: "₦8,000",
    category: "Coffee & Brunch",
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?q=80&w=600",
    websiteUrl: "https://www.instagram.com/artcafe888",
    mapUrl: "https://goo.gl/maps/ArtCafe",
    description: "A cozy spot with eclectic decor. Famous for their coffee and Mediterranean dishes. A great spot to work from."
  },
  {
    id: 20,
    name: "Moist Beach Club",
    area: "Victoria Island",
    type: "Island",
    price: "₦10,000",
    category: "Nightlife",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=600",
    websiteUrl: "https://www.moistbeach.com/",
    mapUrl: "https://goo.gl/maps/Moist",
    description: "If you want to party by the ocean, this is the place. It gets very busy on Friday and Saturday nights."
  },
  {
    id: 21,
    name: "Cactus Restaurant",
    area: "Victoria Island",
    type: "Island",
    price: "₦15,000",
    category: "Food",
    image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?q=80&w=600",
    websiteUrl: "https://www.instagram.com/cactuslagos",
    mapUrl: "https://goo.gl/maps/Cactus",
    description: "Famous for their massive desserts and waterfront terrace. A family-friendly spot that has been around for years."
  },
  {
    id: 22,
    name: "Upbeat Centre",
    area: "Lekki",
    type: "Island",
    price: "₦6,000",
    category: "Activity",
    image: "https://images.unsplash.com/photo-1528659850628-9867c2957963?q=80&w=600",
    websiteUrl: "https://upbeatcentre.com/",
    mapUrl: "https://goo.gl/maps/Upbeat",
    description: "West Africa's first trampoline park. Great for fitness, kids, or just acting like a kid again."
  },
  {
    id: 23,
    name: "Flowershop Cafe",
    area: "Victoria Island",
    type: "Island",
    price: "₦12,000",
    category: "Date Night",
    image: "https://images.unsplash.com/photo-1485686531765-ba63b07829a0?q=80&w=600",
    websiteUrl: "https://www.flowershop.com.ng/",
    mapUrl: "https://goo.gl/maps/Flowershop",
    description: "A cafe inside a flower shop. The smell is amazing and the aesthetics are perfect for a romantic brunch."
  },
  {
    id: 24,
    name: "Kapadoccia",
    area: "Victoria Island",
    type: "Island",
    price: "₦25,000",
    category: "Date Night",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=600",
    websiteUrl: "https://kapadokialagos.com/",
    mapUrl: "https://goo.gl/maps/Kapadoccia",
    description: "Lagos's first cave-themed restaurant. Very dim lighting and unique architecture. It feels like dining in Turkey."
  }
];